name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: code-large

    container:
      image: data-service-docker-local.bart.sec.samsung.net/android:31-system-jfrog
      credentials:
        username: ${{ secrets.BART_USER }}
        password: ${{ secrets.BART_API_KEY }}

    steps:
      - name: ‚¨áÔ∏è Checkout
        uses: code-actions/checkout@v2

      - name: ‚¨áÔ∏è Caching...
        uses: code-actions/cache@v3
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: ‚ö°Ô∏è Check environment (Java & Android SDK)
        run: |
          java --version
          sdkmanager --list

      - name: üê∏ Execute test
        run: ./gradlew testWithLint -x :sample:researchsample:test

      - name: üê∏ Execute Jacoco
        run: ./gradlew jacocoTestReport

      - name: üêã Upload Jacoco Report
        uses: CODE-Actions/upload-artifact@v2
        with:
          name: Jacoco Report
          path: '**/**/build/reports/jacoco'

      - name: Stop gradle for caching
        run: ./gradlew --stop
